@startuml
'https://plantuml.com/class-diagram
skinparam backgroundColor #777777

class Main {
    + migrator
    + scanner
    + deduper
    + main()
}
interface filemigrator.Migrator {
    +MigrateUniqueFiles(string, []string, map[string]common.FileRecord): error
}
interface filescanner.Scanner {
    +ScanDir(bool, []string)
}
interface deduper.DeDuper {
    +DeDuplicate(map[string][]common.FileRecord): common.DeDedupeOutput
}

Migrator <|- Main
DeDuper <|- Main
Scanner <|- Main

@enduml